import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 8,
    paddingTop: 20,
    alignItems: "center",
    backgroundColor: "#f2f2f2",
    position: "relative",
  },
  slide: {
    flex: 1,
    alignItems: "center",
    width: "90%",
    minHeight: 200,
    marginVertical: 10,
    borderRadius: 10,
    backgroundColor: "#fff",
    padding: 10,
    justifyContent: "center",
  },
  cards: {
    width: "95%",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-around",
    marginVertical: 10,
    borderRadius: 10,
    backgroundColor: "#fff",
    padding: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 2,
    justifyContent: "center",
  },
  card: {
    justifyContent: "center",
    alignContent: "center",
    width: "45%",
    maxWidth: 300,
    minHeight: 200,
    marginHorizontal: 5,
    marginVertical: 10,
    backgroundColor: "#fff",
    borderRadius: 10,
    borderRadius: 10,
    padding: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 2,
  },
});
